# Generated by Django 3.2.1 on 2026-04-22 04:35

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atributo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('precio_base', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('precio_costo', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Costo unitario para valorización de activos', max_digits=10)),
                ('tiene_variantes', models.BooleanField(default=False, help_text='Si es True, el producto se vende a través de sus ProductoVariante')),
                ('activo', models.BooleanField(default=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('familia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='catalogo.familia')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ValorAtributo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(max_length=60)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('atributo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores', to='catalogo.atributo')),
            ],
            options={
                'ordering': ['atributo__nombre', 'orden', 'valor'],
                'unique_together': {('atributo', 'valor')},
            },
        ),
        migrations.CreateModel(
            name='ProductoVariante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=60, unique=True)),
                ('precio_override', models.DecimalField(blank=True, decimal_places=2, help_text='Si se define, reemplaza el precio_base del producto', max_digits=10, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variantes', to='catalogo.producto')),
                ('valores', models.ManyToManyField(blank=True, related_name='variantes', to='catalogo.ValorAtributo')),
            ],
            options={
                'ordering': ['producto__nombre', 'sku'],
            },
        ),
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('porcentaje', 'Porcentaje'), ('monto', 'Monto fijo')], max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('canal', models.CharField(choices=[('presencial', 'Presencial'), ('online', 'Online'), ('ambos', 'Ambos')], default='ambos', max_length=20)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('activa', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ofertas', to='catalogo.producto')),
                ('variante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ofertas', to='catalogo.productovariante')),
            ],
            options={
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.AddConstraint(
            model_name='oferta',
            constraint=models.CheckConstraint(check=models.Q(('producto__isnull', False), ('variante__isnull', False), _connector='OR'), name='oferta_tiene_target'),
        ),
        migrations.AddConstraint(
            model_name='oferta',
            constraint=models.CheckConstraint(check=models.Q(('fecha_fin__gte', django.db.models.expressions.F('fecha_inicio'))), name='oferta_fechas_coherentes'),
        ),
    ]
