# Generated by Django 3.2.1 on 2026-04-29 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_auto_20260428_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='colegio',
            name='nombre_buscable',
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
        migrations.AddField(
            model_name='familia',
            name='nombre_buscable',
            field=models.CharField(blank=True, db_index=True, max_length=60),
        ),
        migrations.AddField(
            model_name='producto',
            name='descripcion_buscable',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='nombre_buscable',
            field=models.CharField(blank=True, db_index=True, max_length=200),
        ),
    ]
