# Generated by Django 3.2.1 on 2026-05-14 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_codigo_barras'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='productos/galeria/')),
                ('orden', models.PositiveSmallIntegerField(default=0, help_text='Orden de visualizacion en la galeria (asc).')),
                ('alt', models.CharField(blank=True, help_text='Texto alternativo para accesibilidad. Si vacio, se usa el nombre del producto.', max_length=200)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='catalogo.producto')),
            ],
            options={
                'verbose_name': 'Imagen de galeria',
                'verbose_name_plural': 'Imagenes de galeria',
                'ordering': ['orden', 'creado'],
            },
        ),
    ]
