# Generated by Django 3.2.1 on 2026-05-14 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0003_reciboventa_dte_url_pdf'),
        ('catalogo', '0006_producto_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estrellas', models.PositiveSmallIntegerField(choices=[(1, '1 estrella'), (2, '2 estrellas'), (3, '3 estrellas'), (4, '4 estrellas'), (5, '5 estrellas')])),
                ('titulo', models.CharField(blank=True, max_length=120)),
                ('texto', models.TextField()),
                ('nombre_publico', models.CharField(help_text='Nombre o nick que se publica con la resena.', max_length=80)),
                ('cliente_email', models.EmailField(help_text='Email del autor — NO se publica. Solo para contactar si la dueña necesita validar.', max_length=254)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de revisión'), ('aprobada', 'Aprobada (visible)'), ('rechazada', 'Rechazada')], db_index=True, default='pendiente', max_length=12)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('moderada', models.DateTimeField(blank=True, null=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resenas', to='catalogo.producto')),
                ('recibo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resenas', to='pos.reciboventa')),
            ],
            options={
                'ordering': ['-creado'],
            },
        ),
        migrations.AddConstraint(
            model_name='resena',
            constraint=models.CheckConstraint(check=models.Q(('estrellas__gte', 1), ('estrellas__lte', 5)), name='resena_estrellas_1_5'),
        ),
    ]
