# Generated by Django 3.2.1 on 2026-05-14 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0007_resena'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='oferta',
            index=models.Index(fields=['activa', 'canal', 'fecha_inicio', 'fecha_fin'], name='catalogo_of_activa_53981e_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['activo', 'familia'], name='catalogo_pr_activo_99ea17_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['activo', 'colegio'], name='catalogo_pr_activo_05ed80_idx'),
        ),
    ]
