# Generated by Django 3.2.1 on 2026-05-16 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0008_indices_perf'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productovariante',
            options={'ordering': ['producto__nombre', 'sku'], 'verbose_name': 'variante de producto', 'verbose_name_plural': 'variantes de producto'},
        ),
        migrations.AlterModelOptions(
            name='valoratributo',
            options={'ordering': ['atributo__nombre', 'orden', 'valor'], 'verbose_name': 'valor de atributo', 'verbose_name_plural': 'valores de atributo'},
        ),
    ]
