# Generated by Django 4.2.30 on 2026-05-21 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0009_verbose_names_plurales'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='concentracion',
            field=models.CharField(blank=True, choices=[('EDP', 'Eau de Parfum (EDP)'), ('EDT', 'Eau de Toilette (EDT)'), ('EDC', 'Eau de Cologne (EDC)'), ('BODY', 'Body Spray'), ('SET', 'Set / Estuche')], help_text='Solo para perfumeria. Vacio en otras familias.', max_length=10),
        ),
        migrations.AddField(
            model_name='producto',
            name='familia_olfativa',
            field=models.CharField(blank=True, db_index=True, help_text='Ej: "Oriental Gourmand", "Floral Frutal". Solo perfumes.', max_length=80),
        ),
        migrations.AddField(
            model_name='producto',
            name='genero',
            field=models.CharField(blank=True, choices=[('mujer', 'Mujer'), ('hombre', 'Hombre'), ('unisex', 'Unisex')], help_text='Solo para perfumeria. Permite filtros mujer/hombre/unisex.', max_length=10),
        ),
        migrations.AddField(
            model_name='producto',
            name='marca',
            field=models.CharField(blank=True, db_index=True, max_length=80),
        ),
        migrations.AddField(
            model_name='producto',
            name='medida_ml',
            field=models.PositiveIntegerField(blank=True, help_text='Solo para liquidos (perfumes). Vacio en otras familias.', null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='notas_clave',
            field=models.CharField(blank=True, help_text='Notas olfativas separadas por " · " (ej. "Rosa · Vainilla · Sandalo").', max_length=300),
        ),
    ]
