# Generated by Django 4.2.30 on 2026-05-21 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0010_producto_campos_perfume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productovariante',
            name='sku',
            field=models.CharField(blank=True, help_text='Codigo unico. Si lo dejas en blanco, se autogenera desde marca + nombre + valores de atributos (ej. LATTAFA-YARA-100ML-EDP).', max_length=60, unique=True),
        ),
    ]
