# Generated by Django 4.2.30 on 2026-07-03 14:52

from django.db import migrations, models


def perfumeria_solo_agotado(apps, schema_editor):
    """El negocio maneja 1-2 unidades por perfume — eso es stock NORMAL,
    no 'bajo'. Umbral 0 = para perfumeria solo alerta el agotado."""
    Familia = apps.get_model('catalogo', 'Familia')
    Familia.objects.filter(
        nombre__icontains='perfum',
        umbral_stock_bajo__isnull=True,
    ).update(umbral_stock_bajo=0)


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0011_sku_blank'),
    ]

    operations = [
        migrations.AddField(
            model_name='familia',
            name='umbral_stock_bajo',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Alertar "bajo" cuando el stock sea ≤ a este número. Vacío = umbral general (5). 0 = solo alertar agotados.', null=True, verbose_name='umbral de stock bajo'),
        ),
        migrations.RunPython(perfumeria_solo_agotado, migrations.RunPython.noop),
    ]
