# Generated by Django 4.2.30 on 2026-04-22 02:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bodega', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReciboVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora_venta', models.DateTimeField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Tienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_organizacion', models.CharField(max_length=200, unique=True)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('telefono_contacto', models.CharField(max_length=20)),
                ('correo_contacto', models.EmailField(max_length=254)),
                ('rut_organizacion', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ReciboVentaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_vendida', models.PositiveIntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bodega.producto')),
                ('recibo_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='tienda.reciboventa')),
            ],
        ),
        migrations.AddField(
            model_name='reciboventa',
            name='tienda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recibos', to='tienda.tienda'),
        ),
        migrations.AddField(
            model_name='reciboventa',
            name='vendedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='HistoriaVentas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_venta', models.DateTimeField(auto_now_add=True)),
                ('monto_venta', models.DecimalField(decimal_places=2, max_digits=12)),
                ('recibo_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.reciboventa')),
            ],
        ),
        migrations.CreateModel(
            name='StockTienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_hora_modificacion', models.DateTimeField(auto_now=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_tienda', to='bodega.producto')),
                ('tienda', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='tienda.tienda')),
            ],
            options={
                'unique_together': {('tienda', 'producto')},
            },
        ),
    ]
