# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-16 19:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_auto_20170716_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktienda',
            name='fecha_hora_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
