# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-16 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_stocktienda_fecha_hora_creacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiaventas',
            name='monto_venta',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
