# Generated by Django 4.2.30 on 2026-05-27 17:44

from django.db import migrations, models
import django.db.models.deletion
import ecommerce.models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0011_sku_blank'),
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvisoStockReposicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('token', models.CharField(default=ecommerce.models._generar_token_aviso, help_text='Para construir el link de unsubscribe en el email.', max_length=32, unique=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('notificado', models.DateTimeField(blank=True, help_text='Cuando se envio el email. Null = pendiente.', null=True)),
                ('cancelado', models.DateTimeField(blank=True, help_text='Si el cliente uso el link de unsubscribe. No se borra para tener metricas — solo se marca como cerrado.', null=True)),
                ('variante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avisos_stock', to='catalogo.productovariante')),
            ],
            options={
                'verbose_name': 'aviso de reposición',
                'verbose_name_plural': 'avisos de reposición',
                'ordering': ['-creado'],
                'indexes': [models.Index(fields=['variante', 'notificado'], name='ecommerce_a_variant_c6122d_idx')],
                'unique_together': {('variante', 'email')},
            },
        ),
    ]
