# Generated by Django 4.2.30 on 2026-09-30 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_avisostockreposicion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
