# Generated by Django 4.2.30 on 2026-05-27 17:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('accounts', '0003_admin_resync_permisos'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='perfil', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('recibe_notif_ecommerce', models.BooleanField(default=True, help_text='Si está prendido y el usuario tiene rol DESPACHADOR + esta activo, recibe email cada vez que entra una venta online. Apagalo para pausar notificaciones sin desactivar la cuenta.', verbose_name='Recibe email de pedidos online')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'perfil de usuario',
                'verbose_name_plural': 'perfiles de usuario',
            },
        ),
    ]
