# Generated by Django 3.2.1 on 2026-04-29 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientocaja',
            name='categoria',
            field=models.CharField(choices=[('ingreso_venta', 'Ingreso por venta'), ('costo_inventario', 'Compra de inventario / materia prima'), ('costo_produccion', 'Costo de producción / confección'), ('gasto_operativo', 'Gasto operativo'), ('otro', 'Otro')], default='otro', help_text='Cómo afecta al estado de resultados', max_length=30),
        ),
        migrations.AddIndex(
            model_name='movimientocaja',
            index=models.Index(fields=['categoria'], name='contabilida_categor_784895_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientocaja',
            index=models.Index(fields=['fecha'], name='contabilida_fecha_ef7928_idx'),
        ),
    ]
