# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-13 20:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='fecha_pub',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='fecha publicación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pregunta',
            name='texto_pregunta',
            field=models.CharField(default='esto esta bien?', max_length=2),
            preserve_default=False,
        ),
    ]
