# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-13 22:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20170513_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='texto_pregunta',
            field=models.CharField(max_length=200),
        ),
    ]
