# Generated by Django 3.2.1 on 2026-04-22 04:35

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bodega', '0001_initial'),
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReciboVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canal', models.CharField(choices=[('presencial', 'Presencial'), ('online', 'Online')], max_length=20)),
                ('cliente_nombre', models.CharField(blank=True, max_length=200)),
                ('cliente_email', models.EmailField(blank=True, help_text='Para envío de boleta por correo', max_length=254)),
                ('cliente_rut', models.CharField(blank=True, max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('descuento', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('fallido', 'Fallido'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20)),
                ('payment_provider', models.CharField(blank=True, help_text='tuu | webpay | mercadopago | mock', max_length=30)),
                ('payment_idempotency_key', models.CharField(blank=True, max_length=36, null=True, unique=True)),
                ('payment_reference', models.CharField(blank=True, max_length=120)),
                ('dte_tipo', models.IntegerField(blank=True, help_text='SII: 39=boleta electrónica, 33=factura afecta, etc', null=True)),
                ('dte_folio', models.CharField(blank=True, max_length=50)),
                ('dte_timbre_xml', models.TextField(blank=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recibos', to='bodega.tienda')),
                ('vendedor', models.ForeignKey(blank=True, help_text='Cajero que procesó la venta (solo presencial)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ventas_realizadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='ReciboVentaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(help_text='Snapshot del nombre del producto al momento de la venta', max_length=300)),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descuento', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogo.producto')),
                ('recibo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='pos.reciboventa')),
                ('variante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogo.productovariante')),
            ],
        ),
        migrations.AddConstraint(
            model_name='reciboventadetalle',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('variante__isnull', False), ('producto__isnull', True)), models.Q(('variante__isnull', True), ('producto__isnull', False)), _connector='OR'), name='detalle_variante_xor_producto'),
        ),
        migrations.AddIndex(
            model_name='reciboventa',
            index=models.Index(fields=['canal', 'estado'], name='pos_recibov_canal_9813a1_idx'),
        ),
        migrations.AddIndex(
            model_name='reciboventa',
            index=models.Index(fields=['creado'], name='pos_recibov_creado_4a82bc_idx'),
        ),
    ]
