# Generated by Django 3.2.1 on 2026-04-23 04:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reciboventa',
            name='cliente_usuario',
            field=models.ForeignKey(blank=True, help_text='Cliente registrado que hizo la compra (solo online, opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_online', to=settings.AUTH_USER_MODEL),
        ),
    ]
