# Generated by Django 3.2.1 on 2026-04-28 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_reciboventa_cliente_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='reciboventa',
            name='dte_url_pdf',
            field=models.URLField(blank=True, help_text='URL al PDF de la boleta/factura emitido por el servicio (p.ej. OpenFactura)'),
        ),
    ]
