# Generated by Django 3.2.1 on 2026-05-14 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0003_reciboventa_dte_url_pdf'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='reciboventa',
            index=models.Index(fields=['cliente_email'], name='pos_recibov_cliente_d708c6_idx'),
        ),
    ]
