# Generated by Django 4.2.30 on 2026-05-27 17:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pos', '0004_recibo_email_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='reciboventa',
            name='despachado_en',
            field=models.DateTimeField(blank=True, help_text='Cuando se entrego al cliente / courier. Null = en cola.', null=True),
        ),
        migrations.AddField(
            model_name='reciboventa',
            name='despachado_por',
            field=models.ForeignKey(blank=True, help_text='Quien marco el pedido como despachado.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='despachos_realizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='reciboventa',
            index=models.Index(fields=['canal', 'despachado_en'], name='pos_recibov_canal_c3ce27_idx'),
        ),
    ]
