# Generated by Django 4.2.30 on 2026-07-03 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0005_reciboventa_despachado_en_reciboventa_despachado_por_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reciboventa',
            name='cliente_direccion',
            field=models.TextField(blank=True, help_text='Dirección de envío. Vacía = retiro en local'),
        ),
        migrations.AddField(
            model_name='reciboventa',
            name='cliente_telefono',
            field=models.CharField(blank=True, help_text='Para coordinar entrega / avisos por WhatsApp', max_length=20),
        ),
    ]
