# Generated by Django 4.2.30 on 2026-09-29 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0006_reciboventa_cliente_direccion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reciboventa',
            name='pago_recibido_en',
            field=models.DateTimeField(blank=True, help_text='Cuándo se confirmó el pago. Fallido con fecha = cobrado sin stock, por devolver.', null=True),
        ),
    ]
