# Generated by Django 4.2.30 on 2026-04-22 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atributo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, unique=True)),
                ('ubicacion', models.CharField(blank=True, max_length=30)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_grupo', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventarios', to='bodega.bodega')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=300, null=True)),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('talla', models.CharField(blank=True, choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], max_length=1)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('familia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='bodega.familia')),
            ],
        ),
        migrations.CreateModel(
            name='ProductoAtributo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(blank=True, max_length=30, null=True)),
                ('atributo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bodega.atributo')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atributos', to='bodega.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_proveedor', models.CharField(max_length=30, unique=True)),
                ('direccion', models.CharField(blank=True, max_length=30, null=True)),
                ('telefono', models.CharField(max_length=10)),
                ('correo', models.EmailField(max_length=254)),
                ('cuenta_bco', models.CharField(max_length=20)),
                ('rut_proveedor', models.CharField(max_length=20, unique=True)),
                ('nombre_contacto', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ProductoAtributoValor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(blank=True, max_length=30, null=True)),
                ('producto_atributo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores', to='bodega.productoatributo')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=200)),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('precio_proveedor', models.PositiveIntegerField(default=0)),
                ('largo', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('comerciable', models.BooleanField(default=False)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('mat_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiales', to='bodega.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Inventariolinea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_contada', models.IntegerField(default=0)),
                ('inventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='bodega.inventario')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bodega.producto')),
            ],
        ),
    ]
