# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-03 00:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atributo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_atributo', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, unique=True)),
                ('ubicacion', models.CharField(blank=True, max_length=30)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_familia', models.CharField(max_length=30, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_grupo', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bodega.Bodega')),
            ],
        ),
        migrations.CreateModel(
            name='Inventariolinea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_contada', models.IntegerField(default=0)),
                ('inventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bodega.Inventario')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=200)),
                ('precio', models.FloatField(default=0)),
                ('precio_provedor', models.PositiveIntegerField(default=0)),
                ('largo', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('comerciable', models.BooleanField()),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=200, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=300, null=True)),
                ('precio', models.FloatField(default=0)),
                ('talla', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], max_length=1)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('familia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bodega.Familia')),
            ],
        ),
        migrations.CreateModel(
            name='ProductoAtributo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atributo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bodega.Atributo')),
                ('producto_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bodega.Producto')),
            ],
        ),
        migrations.CreateModel(
            name='ProductoAtributoValor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(blank=True, max_length=30, null=True)),
                ('producto_atributo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bodega.ProductoAtributo')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_proveedor', models.CharField(max_length=30, unique=True)),
                ('direccion', models.CharField(blank=True, max_length=30, null=True)),
                ('telefono', models.CharField(max_length=10)),
                ('correo', models.EmailField(max_length=254)),
                ('cuenta_bco', models.CharField(max_length=20)),
                ('rut_proveedor', models.CharField(max_length=20, unique=True)),
                ('nombre_contacto', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='StockTienda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_contada', models.PositiveIntegerField(default=0)),
                ('producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bodega.Producto')),
            ],
        ),
        migrations.AddField(
            model_name='material',
            name='mat_producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bodega.Producto'),
        ),
        migrations.AddField(
            model_name='inventariolinea',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bodega.Producto'),
        ),
    ]
