# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-11 03:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoLinea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talla', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], max_length=1)),
                ('talla_numero', models.CharField(max_length=2)),
                ('largo', models.IntegerField()),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bodega.Producto')),
            ],
        ),
        migrations.RemoveField(
            model_name='material',
            name='mat_producto',
        ),
        migrations.AddField(
            model_name='material',
            name='mat_producto',
            field=models.ManyToManyField(to='bodega.Producto'),
        ),
    ]
