# Generated by Django 3.2.1 on 2026-04-28 16:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bodega', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='comerciable',
        ),
        migrations.RemoveField(
            model_name='material',
            name='largo',
        ),
        migrations.RemoveField(
            model_name='material',
            name='precio',
        ),
        migrations.RemoveField(
            model_name='material',
            name='precio_proveedor',
        ),
        migrations.RemoveField(
            model_name='material',
            name='producto',
        ),
        migrations.AddField(
            model_name='material',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='material',
            name='costo_unitario_referencia',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Costo aproximado por rollo, en CLP. El costo real de cada compra se guarda en MovimientoMaterial.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='material',
            name='nombre',
            field=models.CharField(max_length=80, unique=True),
        ),
        migrations.CreateModel(
            name='MovimientoMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida')], max_length=20)),
                ('cantidad', models.PositiveIntegerField(help_text='Rollos')),
                ('costo_total', models.DecimalField(decimal_places=2, default=0, help_text='CLP total pagado/movido. En entradas = compra; en salidas = 0 (la plata sale al pagar la confección, no acá).', max_digits=12)),
                ('referencia', models.CharField(blank=True, help_text='Descripción libre (proveedor, factura, lote, etc)', max_length=120)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_material', to='bodega.bodega')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='bodega.material')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_material', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='StockMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=0, help_text='Rollos disponibles')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_materiales', to='bodega.bodega')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_bodegas', to='bodega.material')),
            ],
            options={
                'ordering': ['bodega__nombre', 'material__nombre'],
                'unique_together': {('bodega', 'material')},
            },
        ),
    ]
