# Generated by Django 3.2.1 on 2026-04-28 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
        ('bodega', '0002_auto_20260428_1219'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rendimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidades_por_rollo', models.PositiveIntegerField(help_text='Cuántas unidades de esta variante salen de un rollo (después de cortar). Tallas grandes consumen más tela, así que el número baja.')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendimientos', to='bodega.material')),
                ('variante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendimientos', to='catalogo.productovariante')),
            ],
            options={
                'ordering': ['material__nombre', 'variante__sku'],
                'unique_together': {('material', 'variante')},
            },
        ),
    ]
