# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-03 01:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0002_productoatributo_valor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atributo',
            old_name='nombre_atributo',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='familia',
            old_name='nombre_familia',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='nombre_producto',
            new_name='nombre',
        ),
    ]
