# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-11 15:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0003_auto_20170611_0321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='nombre',
        ),
    ]
