# Generated by Django 3.2.1 on 2026-04-29 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0003_rendimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='nombre_buscable',
            field=models.CharField(blank=True, db_index=True, max_length=80),
        ),
    ]
