# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-11 22:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0005_auto_20170611_1650'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='Historial',
        ),
        migrations.RemoveField(
            model_name='ordenlinea',
            name='orden',
        ),
        migrations.DeleteModel(
            name='Proveedor',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='tienda',
        ),
        migrations.DeleteModel(
            name='Transaccion',
        ),
        migrations.DeleteModel(
            name='Ordencompra',
        ),
        migrations.DeleteModel(
            name='Ordenlinea',
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
        migrations.DeleteModel(
            name='Tienda',
        ),
    ]
