# Generated by Django 3.2.1 on 2026-05-16 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0005_backfill_material_buscable'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material',
            options={'ordering': ['nombre'], 'verbose_name': 'material', 'verbose_name_plural': 'materiales'},
        ),
        migrations.AlterModelOptions(
            name='movimientomaterial',
            options={'ordering': ['-creado'], 'verbose_name': 'movimiento de material', 'verbose_name_plural': 'movimientos de material'},
        ),
        migrations.AlterModelOptions(
            name='movimientostock',
            options={'ordering': ['-creado'], 'verbose_name': 'movimiento de stock', 'verbose_name_plural': 'movimientos de stock'},
        ),
        migrations.AlterModelOptions(
            name='proveedor',
            options={'ordering': ['nombre_proveedor'], 'verbose_name': 'proveedor', 'verbose_name_plural': 'proveedores'},
        ),
        migrations.AlterModelOptions(
            name='stockmaterial',
            options={'ordering': ['bodega__nombre', 'material__nombre'], 'verbose_name': 'stock de material', 'verbose_name_plural': 'stocks de material'},
        ),
        migrations.AlterModelOptions(
            name='stocktienda',
            options={'verbose_name': 'stock por tienda', 'verbose_name_plural': 'stocks por tienda'},
        ),
    ]
